class MainRunner1
{
	public static void main(String[] args)
	{
		System.out.println("Starts main method in MainRunner");
		Rupee rupee=new Rupee();
		int ref=rupee.quantity;
		String ref1=rupee.name;
		double ref2=rupee.price;
		System.out.println("Quantity:"+ref);
		System.out.println("Name:"+ref1);
		System.out.println("Price:"+ref2);
		System.out.println("-------------");
		AirCondition airCondition= new AirCondition();
		int ref3=airCondition.quantity;
		String ref4=airCondition.name;
		double ref5=airCondition.price;
		System.out.println("Quantity:"+ref3);
		System.out.println("Name:"+ref4);
		System.out.println("Price:"+ref5);
		System.out.println("-------------");
		Autorikshaw autorikshaw= new Autorikshaw();
		int ref6=autorikshaw.quantity;
		String ref7=autorikshaw.name;
		double ref8=autorikshaw.price;
		System.out.println("Quantity:"+ref6);
		System.out.println("Name:"+ref7);
		System.out.println("Price:"+ref8);
		System.out.println("-------------");
		AutoDriver autoDriver= new AutoDriver();
		int ref9=autoDriver.quantity;
		String ref10=autoDriver.name;
		double ref11=autoDriver.price;
		System.out.println("Quantity:"+ref9);
		System.out.println("Name:"+ref10);
		System.out.println("Price:"+ref11);
		System.out.println("-------------");
		Rapido rapido= new Rapido();
		int ref12=rapido.quantity;
		String ref13=rapido.name;
		double ref14=rapido.price;
		System.out.println("Quantity:"+ref12);
		System.out.println("Name:"+ref13);
		System.out.println("Price:"+ref14);
		System.out.println("-------------");
		CabCompany cabCompany= new CabCompany();
		int ref15=cabCompany.quantity;
		String ref16=cabCompany.name;
		double ref17=cabCompany.price;
		System.out.println("Quantity:"+ref15);
		System.out.println("Name:"+ref16);
		System.out.println("Price:"+ref17);
		System.out.println("-------------");
		BMTC bmtc= new BMTC();
		int ref18=bmtc.quantity;
		String ref19=bmtc.name;
		double ref20=bmtc.price;
		System.out.println("Quantity:"+ref18);
		System.out.println("Name:"+ref19);
		System.out.println("Price:"+ref20);
		System.out.println("-------------");
		FoodDeliveryCompany foodDeliveryCompany= new FoodDeliveryCompany();
		int ref21=foodDeliveryCompany.quantity;
		String ref22=foodDeliveryCompany.name;
		double ref23=foodDeliveryCompany.price;
		System.out.println("Quantity:"+ref21);
		System.out.println("Name:"+ref22);
		System.out.println("Price:"+ref23);
		System.out.println("-------------");
		Matrimony matrimony= new Matrimony();
		int ref24=matrimony.quantity;
		String ref25=matrimony.name;
		double ref26=matrimony.price;
		System.out.println("Quantity:"+ref24);
		System.out.println("Name:"+ref25);
		System.out.println("Price:"+ref26);
		matrimony.quantity=21;
		matrimony.name="Shadi";
		matrimony.price=2000;
		System.out.println("Updated Quantity:"+matrimony.quantity);
		System.out.println("Updated Name:"+matrimony.name);
		System.out.println("Updated Price:"+matrimony.price);
		System.out.println("-------------");
		Application1 application1= new Application1();
		int ref27=application1.quantity;
		String ref28=application1.name;
		double ref29=application1.price;
		System.out.println("Quantity:"+ref27);
		System.out.println("Name:"+ref28);
		System.out.println("Price:"+ref29);
		application1.quantity=8;
		application1.name="Zoom";
		application1.price=200000;
		System.out.println("Updated Quantity:"+application1.quantity);
		System.out.println("Updated Name:"+application1.name);
		System.out.println("Updated Price:"+application1.price);
		System.out.println("-------------");
		Fruit fruit= new Fruit();
		int ref30=fruit.quantity;
		String ref31=fruit.name;
		double ref32=fruit.price;
		System.out.println("Quantity:"+ref30);
		System.out.println("Name:"+ref31);
		System.out.println("Price:"+ref32);
		fruit.quantity=2;
		fruit.name="Apple";
		fruit.price=200;
		System.out.println("Updated Quantity:"+fruit.quantity);
		System.out.println("Updated Name:"+fruit.name);
		System.out.println("Updated Price:"+fruit.price);
		System.out.println("-------------");
		Juice1 juice1= new Juice1();
		int ref33=juice1.quantity;
		String ref34=juice1.name;
		double ref35=juice1.price;
		System.out.println("Quantity:"+ref33);
		System.out.println("Name:"+ref34);
		System.out.println("Price:"+ref35);
		juice1.quantity=200;
		juice1.name="Apple Juice";
		juice1.price=50;
		System.out.println("Updated Quantity:"+juice1.quantity);
		System.out.println("Updated Name:"+juice1.name);
		System.out.println("Updated Price:"+juice1.price);
		System.out.println("-------------");
		Place1 place1= new Place1();
		int ref36=place1.quantity;
		String ref37=place1.name;
		double ref38=place1.price;
		System.out.println("Quantity:"+ref36);
		System.out.println("Name:"+ref37);
		System.out.println("Price:"+ref38);
		place1.quantity=1;
		place1.name="Shivamogga";
		place1.price=650;
		System.out.println("Updated Quantity:"+place1.quantity);
		System.out.println("Updated Name:"+place1.name);
		System.out.println("Updated Price:"+place1.price);
		System.out.println("-------------");
		AlcoholBrand alcoholBrand= new AlcoholBrand();
		int ref39=alcoholBrand.quantity;
		String ref40=alcoholBrand.name;
		double ref41=alcoholBrand.price;
		System.out.println("Quantity:"+ref39);
		System.out.println("Name:"+ref40);
		System.out.println("Price:"+ref41);
		alcoholBrand.quantity=650;
		alcoholBrand.name="Budwiser Magnum";
		alcoholBrand.price=180;
		System.out.println("Updated Quantity:"+alcoholBrand.quantity);
		System.out.println("Updated Name:"+alcoholBrand.name);
		System.out.println("Updated Price:"+alcoholBrand.price);
		System.out.println("-------------");
		Candy candy= new Candy();
		int ref42=candy.quantity;
		String ref43=candy.name;
		double ref44=candy.price;
		System.out.println("Quantity:"+ref42);
		System.out.println("Name:"+ref43);
		System.out.println("Price:"+ref44);
		candy.quantity=10;
		candy.name="Mango";
		candy.price=1;
		System.out.println("Updated Quantity:"+candy.quantity);
		System.out.println("Updated Name:"+candy.name);
		System.out.println("Updated Price:"+candy.price);
		System.out.println("-------------");
		Medicine1 medicine1= new Medicine1();
		int ref45=medicine1.quantity;
		String ref46=medicine1.name;
		double ref47=medicine1.price;
		System.out.println("Quantity:"+ref45);
		System.out.println("Name:"+ref46);
		System.out.println("Price:"+ref47);
		medicine1.quantity=10;
		medicine1.name="DOLO650";
		medicine1.price=200;
		System.out.println("Updated Quantity:"+medicine1.quantity);
		System.out.println("Updated Name:"+medicine1.name);
		System.out.println("Updated Price:"+medicine1.price);
		System.out.println("-------------");
		Food food= new Food();
		int ref48=food.quantity;
		String ref49=food.name;
		double ref50=food.price;
		System.out.println("Quantity:"+ref48);
		System.out.println("Name:"+ref49);
		System.out.println("Price:"+ref50);
		food.quantity=2;
		food.name="Biriyani";
		food.price=400;
		System.out.println("Updated Quantity:"+food.quantity);
		System.out.println("Updated Name:"+food.name);
		System.out.println("Updated Price:"+food.price);
		System.out.println("-------------");

		System.out.println("Ends main method in MainRunner");

	}
}